exclude: ".vscode/*"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.2
    hooks:
    - id: go-fmt
